#spring:
#  application:
#    name: ProductCD
#  jpa:
#    database: ${DATABASE:postgresql}
#    database-platform: ${SQL_DIALECT:org.hibernate.dialect.PostgreSQL10Dialect}
#    generate-ddl: false
#    hibernate:
#      ddl-auto: update
#
#  datasource:
#    username: ${DB_USER:postgres}
#    password: ${DB_PASS:896699}
#    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/products
#    driver-class-name: org.postgresql.Driver

server:
  port: ${PORT:8082}